name: GitHub Actions - Workflow Dispatch choice Template

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Escolha uma tag"
        required: true
        default: "tag1"
        type: choice
        options:
          - tag1
          - tag2
          - tag3

jobs:
  show-choice:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar a escolha
        run: echo "Você escolheu a opção: ${{ github.event.inputs.tag }}"
