name: GitHub Actions - Workflow run Super Combinado
on:
  workflow_run:
    workflows: ["GitHub Actions - Trigger Template"]
    types: [requested, in_progress, completed]
jobs:
  super_combinado_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Workflow run Super Combinado executado
